New release for spack.
ytopt-team/ytopt pull request #26
Opened 2022-06-06 19:54 UTC by Kerilk

This PR fixes the python build system that was not picking up the ytopt files, resulting in empty pip installation.
This will require a new release in order for spack to get a valid version to work with.

Is the main branch ready for release otherwise? If so, I will create a new tag.

2022-06-06 21:26 UTC, wuxf99 commented
I think that the main branch is ready for the release.

2022-06-06 22:14 UTC, jaehoonkoo requested changes
I am getting errors:

```
Uncaught exception <class 'TypeError'>: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updatesTraceback (most recent call last):
  File "/Users/jkoo/opt/anaconda3/envs/test_ytune/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jkoo/opt/anaconda3/envs/test_ytune/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jkoo/research/github/ytopt_test/ytopt/ytopt/search/ambs.py", line 125, in <module>
    search = AMBS(**vars(args))
  File "/Users/jkoo/research/github/ytopt_test/ytopt/ytopt/search/ambs.py", line 45, in __init__
    super().__init__(**kwargs)
  File "/Users/jkoo/research/github/ytopt_test/ytopt/ytopt/search/search.py", line 41, in __init__
    self.evaluator = Evaluator.create(self.problem, method=evaluator, redis_address=redis_address)
  File "/Users/jkoo/research/github/ytopt_test/ytopt/ytopt/evaluator/evaluate.py", line 76, in create
    from ytopt.evaluator.ray_evaluator import RayEvaluator
  File "/Users/jkoo/research/github/ytopt_test/ytopt/ytopt/evaluator/ray_evaluator.py", line 9, in <module>
    import ray
  File "/Users/jkoo/opt/anaconda3/envs/test_ytune/lib/python3.7/site-packages/ray/__init__.py", line 108, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 115, in init ray._raylet
  File "/Users/jkoo/opt/anaconda3/envs/test_ytune/lib/python3.7/site-packages/ray/exceptions.py", line 7, in <module>
    from ray.core.generated.common_pb2 import RayException, Language, PYTHON
  File "/Users/jkoo/opt/anaconda3/envs/test_ytune/lib/python3.7/site-packages/ray/core/generated/common_pb2.py", line 15, in <module>
    from . import runtime_env_common_pb2 as src_dot_ray_dot_protobuf_dot_runtime__env__common__pb2
  File "/Users/jkoo/opt/anaconda3/envs/test_ytune/lib/python3.7/site-packages/ray/core/generated/runtime_env_common_pb2.py", line 42, in <module>
    serialized_options=None, json_name='packages', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  File "/Users/jkoo/opt/anaconda3/envs/test_ytune/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
Downgrading protobuf <= 3.19.x worked. `pip install protobuf==3.19`

```
(test_ytune) ➜  mmm_problem (main) ✔ pip install protobuf==3.19
Collecting protobuf==3.19
  Downloading protobuf-3.19.0-cp37-cp37m-macosx_10_9_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 7.3 MB/s 
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.21.1
    Uninstalling protobuf-4.21.1:
      Successfully uninstalled protobuf-4.21.1
Successfully installed protobuf-3.19.0
(test_ytune) ➜  mmm_problem (main) ✔ 
(test_ytune) ➜  mmm_problem (main) ✔ python -m ytopt.search.ambs --evaluator ray --problem problem.Problem --max-evals=5 --learner RF
............self.KAPPA 1.96
............self.learner RF
............self.acq_func gp_hedge
............self.SEED 12345
............n_init 10
(compute_objective pid=38245) CONFIG: {'BLOCK_SIZE': 2}
(compute_objective pid=38245) OUTPUT:%f 0.224
(compute_objective pid=38245) CONFIG: {'BLOCK_SIZE': 8}
(compute_objective pid=38245) OUTPUT:%f 0.048
(compute_objective pid=38245) CONFIG: {'BLOCK_SIZE': 6}
(compute_objective pid=38245) OUTPUT:%f 0.068
(compute_objective pid=38245) CONFIG: {'BLOCK_SIZE': 7}
(compute_objective pid=38245) OUTPUT:%f 0.082
(compute_objective pid=38245) CONFIG: {'BLOCK_SIZE': 1}
```
Can we add `'protobuf<=3.19' `in the `setup.py`?

2022-06-06 22:53 UTC, Kerilk commented
Well the issue here is that this dependency is pulled from another package, and this package should have it's dependency fixed. Do you know which package pulls protobuf?

For reference, here are the 4 PRs I opened to spack to fix the current release:
 * https://github.com/spack/spack/pull/31016
 * https://github.com/spack/spack/pull/31015
 * https://github.com/spack/spack/pull/31014
 * https://github.com/spack/spack/pull/31013

2022-06-06 23:39 UTC, jaehoonkoo commented
Certainly, Ray needs protobuf https://github.com/ray-project/ray/blob/master/python/setup.py#L292 

and Ray is needed when ytopt is installed.

```
(test_ytune) ➜  ytopt (main) ✔ pip install -e . 
Obtaining file:///Users/jkoo/research/github/ytopt_test/ytopt
Requirement already satisfied: numpy in /Users/jkoo/.local/lib/python3.7/site-packages (from ytopt==0.0.4) (1.21.5)
Requirement already satisfied: scikit-learn>=1.0.0 in /Users/jkoo/opt/anaconda3/envs/test_ytune/lib/python3.7/site-packages (from ytopt==0.0.4) (1.0.2)
Requirement already satisfied: tqdm in /Users/jkoo/.local/lib/python3.7/site-packages (from ytopt==0.0.4) (4.62.3)
Requirement already satisfied: joblib in /Users/jkoo/.local/lib/python3.7/site-packages (from ytopt==0.0.4) (1.1.0)
Collecting deap
  Using cached deap-1.3.1-cp37-cp37m-macosx_10_14_x86_64.whl (109 kB)
Collecting ray[debug]
  Downloading ray-1.12.1-cp37-cp37m-macosx_10_15_intel.whl (56.0 MB)
     |████████████████████████████████| 56.0 MB 297 kB/s 
Collecting mpi4py>=3.0.0
  Using cached mpi4py-3.1.3-cp37-cp37m-macosx_10_9_x86_64.whl
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/jkoo/.local/lib/python3.7/site-packages (from scikit-learn>=1.0.0->ytopt==0.0.4) (3.0.0)
Requirement already satisfied: scipy>=1.1.0 in /Users/jkoo/.local/lib/python3.7/site-packages (from scikit-learn>=1.0.0->ytopt==0.0.4) (1.7.3)
WARNING: ray 1.12.1 does not provide the extra 'debug'
Collecting msgpack<2.0.0,>=1.0.0
  Downloading msgpack-1.0.4-cp37-cp37m-macosx_10_9_x86_64.whl (72 kB)
     |████████████████████████████████| 72 kB 1.3 MB/s 
Collecting filelock
  Downloading filelock-3.7.1-py3-none-any.whl (10 kB)
Requirement already satisfied: pyyaml in /Users/jkoo/opt/anaconda3/envs/test_ytune/lib/python3.7/site-packages (from ray[debug]->ytopt==0.0.4) (6.0)
Collecting grpcio<=1.43.0,>=1.28.1
  Using cached grpcio-1.43.0-cp37-cp37m-macosx_10_10_x86_64.whl (4.1 MB)
Collecting attrs
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting frozenlist
  Downloading frozenlist-1.3.0-cp37-cp37m-macosx_10_9_x86_64.whl (35 kB)
Collecting aiosignal
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Requirement already satisfied: requests in /Users/jkoo/.local/lib/python3.7/site-packages (from ray[debug]->ytopt==0.0.4) (2.27.1)
Collecting virtualenv
  Downloading virtualenv-20.14.1-py2.py3-none-any.whl (8.8 MB)
     |████████████████████████████████| 8.8 MB 899 kB/s 
Collecting click>=7.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 3.2 MB/s 
Collecting jsonschema
  Downloading jsonschema-4.6.0-py3-none-any.whl (80 kB)
     |████████████████████████████████| 80 kB 3.6 MB/s 
Collecting protobuf>=3.15.3
  Downloading protobuf-4.21.1-cp37-abi3-macosx_10_9_universal2.whl (483 kB)
     |████████████████████████████████| 483 kB 3.7 MB/s 
Requirement already satisfied: importlib-metadata in /Users/jkoo/.local/lib/python3.7/site-packages (from click>=7.0->ray[debug]->ytopt==0.0.4) (4.10.0)
Requirement already satisfied: six>=1.5.2 in /Users/jkoo/.local/lib/python3.7/site-packages (from grpcio<=1.43.0,>=1.28.1->ray[debug]->ytopt==0.0.4) (1.16.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /Users/jkoo/.local/lib/python3.7/site-packages (from importlib-metadata->click>=7.0->ray[debug]->ytopt==0.0.4) (4.0.1)
Requirement already satisfied: zipp>=0.5 in /Users/jkoo/.local/lib/python3.7/site-packages (from importlib-metadata->click>=7.0->ray[debug]->ytopt==0.0.4) (3.7.0)
```

2022-06-07 02:29 UTC, Kerilk commented
OK that won't be an issue with spack, as the version of ray we use there is quite old and does not depend on protobuf (v0.8.7).
In the meantime, the ray project seems to be aware of the issue:
https://github.com/ray-project/ray/issues/25282
so they will fix it soon I expect.

2022-06-07 19:35 UTC, merged